import { useEffect, useMemo, useState } from 'react';
import { AdminApiError, acknowledge, api, clearToken, currentUser, history, incident, login, publicDashboard, queue, saveToken, submitResolution, verification, type QueueRow, type User } from './http';

type View = 'overview' | 'queue' | 'impact' | 'analytics' | 'history';

export function AdminApp() {
  const [user, setUser] = useState<User | null>(null);
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('civic-admin-theme') === 'dark');
  const [checking, setChecking] = useState(true);
  useEffect(() => { document.documentElement.dataset.theme = darkMode ? 'dark' : 'light'; localStorage.setItem('civic-admin-theme', darkMode ? 'dark' : 'light'); }, [darkMode]);
  useEffect(() => { currentUser().then((x) => setUser(x.user)).catch(() => { clearToken(); setUser(null); }).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="center-screen">Checking administrative access…</div>;
  if (!user) return <Login onLogin={setUser} darkMode={darkMode} onToggleTheme={() => setDarkMode((x) => !x)} />;
  if (!['administrator', 'supervisor'].includes(user.role)) return <div className="center-screen"><h1>Administrative access required</h1><p>Your account does not have access to this dashboard.</p><button onClick={() => { clearToken(); setUser(null); }}>Sign out</button></div>;
  return <Dashboard user={user} darkMode={darkMode} onToggleTheme={() => setDarkMode((x) => !x)} onSignOut={() => { clearToken(); setUser(null); }} />;
}

function Login({ onLogin, darkMode, onToggleTheme }: { onLogin: (user: User) => void; darkMode: boolean; onToggleTheme: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try {
      const result = await login(email, password);
      if (!['administrator', 'supervisor'].includes(result.user.role)) {
        clearToken(); setError('This account is valid, but it is not authorized for the administration console.'); return;
      }
      saveToken(result.token); onLogin(result.user);
    } catch (err) {
      if (err instanceof AdminApiError) {
        if (err.code === 'EMAIL_NOT_VERIFIED') setError('Your account is not verified yet. Verify it before signing in.');
        else if (err.code === 'INVALID_CREDENTIALS' || err.status === 401) setError('The email or password is incorrect.');
        else setError(err.message);
      } else setError('The administrative service could not be reached. Check that the API is running and try again.');
    } finally { setBusy(false); }
  }
  return <main className="login-shell"><button className="theme-toggle login-theme" onClick={onToggleTheme} aria-label="Toggle dark mode">{darkMode ? '☀ Light' : '☾ Dark'}</button><section className="login-card"><span className="brand-mark">Civic<span>Issue</span></span><p className="eyebrow">ADMINISTRATION CONSOLE</p><h1>Operate from the incident picture.</h1><p className="muted">Sign in with a supervisor or administrator account to view live civic reports and coordinated work.</p><form onSubmit={submit}><label>Email<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input type="password" required minLength={12} value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <div className="alert">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Signing in…' : 'Open dashboard'}</button></form></section></main>;
}

function Dashboard({ user, darkMode, onToggleTheme, onSignOut }: { user: User; darkMode: boolean; onToggleTheme: () => void; onSignOut: () => void }) {
  const [view, setView] = useState<View>('overview'); const [rows, setRows] = useState<QueueRow[]>([]); const [historyRows, setHistoryRows] = useState<QueueRow[]>([]); const [summary, setSummary] = useState<Record<string, unknown>>({}); const [selected, setSelected] = useState<string | null>(null); const [detail, setDetail] = useState<any>(null); const [error, setError] = useState(''); const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  async function refresh() { try { setError(''); const [nextRows, dashboard] = await Promise.all([queue(), publicDashboard()]); setRows(nextRows); setSummary(dashboard.summary); try { setHistoryRows(await history()); } catch { setHistoryRows([]); } setLastUpdated(new Date()); } catch (err) { setError(err instanceof AdminApiError ? err.message : 'Live administrative data is temporarily unavailable.'); } }
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 15000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!selected) { setDetail(null); return; } (async () => { try { const next = await incident(selected); setDetail(next); await acknowledge(selected); } catch { setDetail(null); } })(); }, [selected]);
  const active = rows.filter((r) => !['resolved', 'closed'].includes(r.status)); const high = rows.filter((r) => ['HIGH', 'CRITICAL'].includes(r.priority)); const atRisk = active.filter((r) => r.slaDueAt && new Date(r.slaDueAt).getTime() < Date.now() + 86400000); const recurring = rows.filter((r) => Number(r.supportingReports) > 1);
  const sorted = useMemo(() => [...rows].sort((a, b) => Number(b.impactScore) - Number(a.impactScore)), [rows]);
  return <div className="admin-shell"><header className="admin-topbar"><div><span className="brand-mark">Civic<span>Issue</span></span><span className="console-label">Municipal operations</span></div><div className="top-actions"><span className="live-dot">Live data</span><span>{user.displayName}</span><button className="theme-toggle" onClick={onToggleTheme} aria-label="Toggle dark mode">{darkMode ? '☀ Light' : '☾ Dark'}</button><button onClick={onSignOut}>Sign out</button></div></header><div className="admin-body"><aside className="admin-sidebar"><p className="eyebrow">CONTROL CENTER</p>{([['overview','Overview'],['queue','Incident queue'],['impact','Impact & priority'],['history','History'],['analytics','Analytics']] as [View,string][]).map(([id,label]) => <button key={id} className={view === id ? 'side-link active' : 'side-link'} onClick={() => setView(id)}>{label}</button>)}<div className="side-note"><strong>Decision support</strong><p>Scores, estimates, predictions, and hypotheses assist review. They do not dispatch work automatically.</p></div></aside><main className="admin-content"><div className="admin-heading"><div><p className="eyebrow">{user.role.toUpperCase()} WORKSPACE</p><h1>{view === 'overview' ? 'Civic operations overview' : view === 'queue' ? 'Incident queue' : view === 'impact' ? 'Impact & priority' : view === 'history' ? 'Resolved problem history' : 'Governance analytics'}</h1><p className="muted">{lastUpdated ? `Updated ${lastUpdated.toLocaleTimeString()}. Refreshes every 15 seconds.` : 'Loading live municipal data…'}</p></div><button className="refresh" onClick={refresh}>Refresh now</button></div>{error && <div className="alert">{error}</div>}{view === 'overview' && <Overview rows={rows} active={active} high={high} atRisk={atRisk} recurring={recurring} summary={summary} onSelect={setSelected} />}{view === 'queue' && <QueueView rows={sorted} onSelect={setSelected} />}{view === 'impact' && <ImpactView rows={sorted} onSelect={setSelected} />}{view === 'history' && <HistoryView rows={historyRows} onSelect={setSelected} />}{view === 'analytics' && <Analytics summary={summary} rows={rows} />}{selected && <IncidentDrawer detail={detail} onClose={() => setSelected(null)} />}</main></div></div>;
}

function Metric({ value, label, tone = '' }: { value: string | number; label: string; tone?: string }) { return <div className={`metric ${tone}`}><strong>{value}</strong><span>{label}</span></div>; }
function Overview({ rows, active, high, atRisk, recurring, summary, onSelect }: { rows: QueueRow[]; active: QueueRow[]; high: QueueRow[]; atRisk: QueueRow[]; recurring: QueueRow[]; summary: Record<string, unknown>; onSelect: (id: string) => void }) { return <><section className="hero"><div><p className="eyebrow">INCIDENT INTELLIGENCE</p><h2>See the physical problems behind the reports.</h2><p>Every citizen report is preserved as evidence. Nearby reports are organized into incidents for prioritization, coordination, and resolution.</p></div><div className="hero-stat"><strong>{rows.length}</strong><span>incidents in operational view</span></div></section><section className="metric-grid"><Metric value={active.length} label="Active incidents" /><Metric value={high.length} label="High impact" tone="danger" /><Metric value={atRisk.length} label="SLA risk in 24h" tone="warning" /><Metric value={recurring.length} label="Multi-report incidents" /></section><section className="dashboard-grid"><div className="panel wide"><div className="panel-heading"><div><p className="eyebrow">PRIORITY WORKLIST</p><h2>What needs attention</h2></div><span className="count">{active.length}</span></div><IncidentRows rows={active.slice(0, 8)} onSelect={onSelect} empty="No active incidents. New reports will appear here after clustering." /></div><div className="panel"><p className="eyebrow">GOVERNANCE SIGNALS</p><h2>Public picture</h2><div className="signal-list"><div><span>Total reports</span><strong>{String(summary.total_reports ?? '—')}</strong></div><div><span>Total incidents</span><strong>{String(summary.total_incidents ?? '—')}</strong></div><div><span>Resolved incidents</span><strong>{String(summary.resolved_incidents ?? '—')}</strong></div><div><span>High-impact incidents</span><strong>{String(summary.high_impact_incidents ?? '—')}</strong></div></div></div></section></>; }
function QueueView({ rows, onSelect }: { rows: QueueRow[]; onSelect: (id: string) => void }) { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">LIVE QUEUE</p><h2>All operational incidents</h2></div><span className="count">{rows.length}</span></div><IncidentRows rows={rows} onSelect={onSelect} empty="No incidents are currently in the queue." /></section>; }
function ImpactView({ rows, onSelect }: { rows: QueueRow[]; onSelect: (id: string) => void }) { return <section className="panel"><p className="eyebrow">DECISION SUPPORT</p><h2>Prioritized by public impact</h2><p className="muted">Impact score combines available severity, safety, population, location, duration, recurrence, and supporting-report evidence. It is not an automatic dispatch decision.</p><IncidentRows rows={rows} onSelect={onSelect} empty="Impact analysis is not available for current incidents." /></section>; }
function HistoryView({ rows, onSelect }: { rows: QueueRow[]; onSelect: (id: string) => void }) { return <section className="panel"><p className="eyebrow">CITIZEN-CONFIRMED RESOLUTIONS</p><h2>Resolved problem history</h2><p className="muted">Only problems confirmed by a citizen are archived here for future analysis. Resolution photos and repair notes remain available in each incident record.</p>{!rows.length ? <div className="empty">No citizen-confirmed resolutions are recorded yet.</div> : <div className="incident-rows">{rows.map((r: any) => <button className="incident-row" key={r.incidentId} onClick={() => onSelect(r.incidentId)}><div className="row-main"><strong>{r.priority}</strong><span>{r.status}</span><small>{r.categoryName}</small></div><div className="row-data"><span><b>{new Date(r.resolvedAt ?? r.createdAt).toLocaleDateString()}</b><small>confirmed on</small></span><span><b>{r.supportingReports}</b><small>reports</small></span><span><b>{r.impactScore}</b><small>impact score</small></span></div><div className="row-arrow">→</div></button>)}</div>}</section>; }
function Analytics({ summary, rows }: { summary: Record<string, unknown>; rows: QueueRow[] }) { const categories = [...new Set(rows.map((r) => r.categoryId))]; return <section className="panel"><p className="eyebrow">AGGREGATED VIEW</p><h2>Governance analytics</h2><div className="metric-grid compact"><Metric value={String(summary.total_reports ?? '—')} label="Reports received" /><Metric value={String(summary.total_incidents ?? '—')} label="Physical incidents" /><Metric value={categories.length} label="Issue categories represented" /></div><p className="muted">Public-safe analytics remain separate from private citizen identity and precise personal location data.</p></section>; }
function IncidentRows({ rows, onSelect, empty }: { rows: QueueRow[]; onSelect: (id: string) => void; empty: string }) { if (!rows.length) return <div className="empty">{empty}</div>; return <div className="incident-rows">{rows.map((r) => <button className="incident-row" key={r.incidentId} onClick={() => onSelect(r.incidentId)}><div className="row-main"><strong>{r.priority}</strong><span>{r.status.replaceAll('_', ' ')}</span><small>{r.categoryName}</small></div><div className="row-data"><span><b>{Number(r.impactScore).toFixed(0)}</b><small>impact</small></span><span><b>{r.supportingReports}</b><small>reports</small></span><span><b>{r.supportingVotes ?? 0}</b><small>upvotes</small></span><span><b>{r.affectedPopulation ?? '—'}</b><small>estimated affected</small></span></div><div className="row-arrow">→</div></button>)}</div>; }
function IncidentDrawer({ detail, onClose }: { detail: any; onClose: () => void }) {
  const [proof, setProof] = useState<File | null>(null); const [note, setNote] = useState(''); const [verificationState, setVerificationState] = useState<any>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { if (detail?.id) verification(detail.id).then(setVerificationState).catch(() => setVerificationState(null)); }, [detail?.id]);
  async function submitProof() {
    if (!detail || !proof) { setMessage('Select a resolution photo before declaring this incident resolved.'); return; }
    if (!proof.type.startsWith('image/')) { setMessage('Resolution proof must be an image file.'); return; }
    setBusy(true); setMessage('');
    try {
      const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('FILE_READ_FAILED')); reader.readAsDataURL(proof); });
      const hash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', await proof.arrayBuffer()))).map((x) => x.toString(16).padStart(2, '0')).join('');
      const result = await submitResolution(detail.id, { resolutionLatitude: detail.latitude ?? null, resolutionLongitude: detail.longitude ?? null, note: note.trim() || undefined, media: [{ storageKey: `admin-resolution/${detail.id}/${Date.now()}-${proof.name}`, mediaType: proof.type, capturedAt: new Date().toISOString(), sha256: hash, dataUrl }] });
      setMessage(result.overall === 'PASS' ? 'Resolution verified. The incident is now declared resolved.' : 'Proof submitted for verification review. The incident remains pending until the evidence is sufficient.');
      setProof(null); setNote(''); setVerificationState(result); window.setTimeout(() => window.location.reload(), 900);
    } catch (err) { setMessage(err instanceof AdminApiError ? err.message : 'The resolution proof could not be submitted.'); } finally { setBusy(false); }
  }
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={(e) => e.stopPropagation()}><button className="close" onClick={onClose}>×</button>{!detail ? <p>Loading incident detail…</p> : <><p className="eyebrow">INCIDENT DETAIL</p><h2>{detail.id}</h2><span className="status">{detail.status}</span><div className="drawer-facts"><div><span>Supporting reports</span><strong>{detail.reports?.length ?? 0}</strong></div><div><span>Location</span><strong>{detail.latitude?.toFixed?.(5) ?? '—'}, {detail.longitude?.toFixed?.(5) ?? '—'}</strong></div></div><h3>Evidence timeline</h3><ol>{(detail.history ?? []).map((h: any) => <li key={h.id}>{h.eventType}<small>{new Date(h.occurredAt).toLocaleString()}</small></li>)}</ol><section className="resolution-box"><p className="eyebrow">RESOLUTION PROOF</p><h3>Declare this problem resolved</h3><p className="muted">Upload a photo showing the completed repair. The evidence is checked against the incident location before the status changes.</p>{verificationState?.overall_result && <p className="verification-result">Latest verification: {verificationState.overall_result}</p>}{verificationState?.media?.[0]?.metadata?.dataUrl && <img className="proof-preview" src={verificationState.media[0].metadata.dataUrl} alt="Submitted resolution proof" />}<label>Repair photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setProof(e.target.files?.[0] ?? null)} /></label>{proof && <p className="file-name">Selected: {proof.name}</p>}<label>Resolution note <textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="What was repaired?" maxLength={2000} /></label>{message && <div className="alert">{message}</div>}<button className="primary" disabled={busy || detail.status === 'resolved' || detail.status === 'closed'} onClick={submitProof}>{busy ? 'Checking proof…' : detail.status === 'resolved' || detail.status === 'closed' ? 'Already resolved' : 'Submit proof and resolve'}</button></section><p className="muted">Resolution status is based on the submitted evidence and remains auditable in the incident timeline.</p></>}</aside></div>;
}
