import {db} from '../lib/database.js';
import {assertIncidentTransition} from './types.js';
import type {IncidentStatus} from './types.js';
import { calculateIncidentImpact } from '../impact/service.js';
export async function listIncidentQueue(filters:{departmentId?:string;wardId?:string;status?:IncidentStatus}={}){
 const where:string[]=[];const values:any[]=[];for(const [column,key] of [['department_id','departmentId'],['ward_id','wardId'],['status','status']] as const){const value=filters[key];if(value){values.push(value);where.push(`i.${column}=$${values.length}`);}}
 const {rows}=await db.query(`SELECT i.id AS "incidentId",i.category_id AS "categoryId",ic.name AS "categoryName",i.department_id AS "departmentId",i.ward_id AS "wardId",i.status,i.created_at AS "createdAt",ST_Y(i.location) AS latitude,ST_X(i.location) AS longitude,COUNT(DISTINCT r.id)::int AS "supportingReports",COUNT(DISTINCT r.citizen_id)::int AS "supportingCitizens",COUNT(DISTINCT rv.id)::int AS "supportingVotes",COALESCE((SELECT score FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),0) AS "impactScore",COALESCE((SELECT priority FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),'LOW') AS priority,COALESCE((SELECT estimated_population FROM incident_population_estimates p WHERE p.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),0) AS "affectedPopulation",(SELECT MIN(due_at) FROM assignments a WHERE a.incident_id=i.id AND a.status NOT IN ('completed','cancelled')) AS "slaDueAt" FROM incidents i JOIN issue_categories ic ON ic.id=i.category_id LEFT JOIN reports r ON r.incident_id=i.id LEFT JOIN report_votes rv ON rv.report_id=r.id ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY i.id,ic.name ORDER BY "impactScore" DESC,"slaDueAt" NULLS LAST,i.created_at ASC`,values);return rows;
}
export async function acknowledgeIncident(id:string,actorId:string){
 const reports=(await db.query(`SELECT id,citizen_id,work_status FROM reports WHERE incident_id=$1 AND work_status='REPORTED'`,[id])).rows;
 if(!reports.length)return {acknowledged:0};
 await db.query('BEGIN');try{for(const report of reports){await db.query(`UPDATE reports SET work_status='ACKNOWLEDGED',updated_at=now() WHERE id=$1`,[report.id]);await db.query(`INSERT INTO report_status_history(report_id,actor_user_id,from_status,to_status,note) VALUES($1,$2,'REPORTED','ACKNOWLEDGED','Administrator opened the incident for municipal review')`,[report.id,actorId]);if(report.citizen_id)await db.query(`INSERT INTO report_notifications(user_id,report_id,type,title,body) VALUES($1,$2,'ACKNOWLEDGED','Report acknowledged','Your complaint has been acknowledged and is now under municipal review.')`,[report.citizen_id,report.id]);}await db.query(`INSERT INTO incident_history(incident_id,actor_user_id,event_type,details) VALUES($1,$2,'REPORTS_ACKNOWLEDGED',$3)`,[id,actorId,JSON.stringify({count:reports.length})]);await db.query('COMMIT');return {acknowledged:reports.length};}catch(e){await db.query('ROLLBACK');throw e;}
}
export async function listResolvedIncidentHistory(){
 const {rows}=await db.query(`SELECT i.id AS "incidentId",i.category_id AS "categoryId",ic.name AS "categoryName",i.status,i.created_at AS "createdAt",i.resolved_at AS "resolvedAt",ST_Y(i.location) AS latitude,ST_X(i.location) AS longitude,COUNT(DISTINCT r.id)::int AS "supportingReports",COALESCE((SELECT score FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),0) AS "impactScore",COALESCE((SELECT priority FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),'LOW') AS priority,(SELECT s.note FROM resolution_submissions s WHERE s.incident_id=i.id ORDER BY s.submitted_at DESC LIMIT 1) AS "resolutionNote" FROM incidents i JOIN issue_categories ic ON ic.id=i.category_id LEFT JOIN reports r ON r.incident_id=i.id WHERE i.status IN ('resolved','closed') GROUP BY i.id,ic.name ORDER BY i.resolved_at DESC NULLS LAST,i.created_at DESC`);
 return rows;
}
export async function getIncident(id:string){
 const incident=(await db.query(`SELECT i.*,(SELECT x.infrastructure_id FROM infrastructure_incidents x WHERE x.incident_id=i.id LIMIT 1) infrastructure_id,ST_Y(i.location) latitude,ST_X(i.location) longitude,COALESCE((SELECT score FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),0) impact_score_latest,COALESCE((SELECT priority FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),'LOW') priority,(SELECT estimated_population FROM incident_population_estimates p WHERE p.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1) affected_population_latest FROM incidents i WHERE i.id=$1`,[id])).rows[0];if(!incident)return null;
 const reports=(await db.query(`SELECT r.id,r.description,r.work_status AS "workStatus",r.reported_at AS "reportedAt",ST_Y(r.location) latitude,ST_X(r.location) longitude,r.address,r.citizen_id IS NOT NULL AS "hasCitizen",(SELECT COUNT(*) FROM media_assets m WHERE m.report_id=r.id)::int AS "photoCount" FROM reports r WHERE r.incident_id=$1 ORDER BY r.reported_at`,[id])).rows;
 const assignments=(await db.query(`SELECT a.id,a.status,a.assigned_at AS "assignedAt",a.due_at AS "dueAt",a.assignee_user_id AS "assigneeUserId",a.team_id AS "teamId" FROM assignments a WHERE a.incident_id=$1 ORDER BY a.assigned_at DESC`,[id])).rows;
 const history=(await db.query(`SELECT id,event_type AS "eventType",details,occurred_at AS "occurredAt" FROM incident_history WHERE incident_id=$1 ORDER BY occurred_at DESC`,[id])).rows;return {...incident,reports,assignments,history};
}
export async function updateIncidentStatus(id:string,actorId:string,to:IncidentStatus,note?:string){
 const current=(await db.query(`SELECT status FROM incidents WHERE id=$1`,[id])).rows[0];if(!current)throw new Error('INCIDENT_NOT_FOUND');assertIncidentTransition(current.status,to);
 if(to==='resolved'){const pending=(await db.query(`SELECT COUNT(*)::int count FROM incident_tasks WHERE incident_id=$1 AND status NOT IN ('COMPLETED','CANCELLED')`,[id])).rows[0]?.count??0;if(Number(pending)>0)throw new Error('CROSS_DEPARTMENT_TASKS_INCOMPLETE');}
 if(to==='resolved'){const reports=(await db.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER (WHERE work_status='CONFIRMED')::int AS confirmed FROM reports WHERE incident_id=$1`,[id])).rows[0];if(Number(reports?.total??0)===0||Number(reports.confirmed??0)!==Number(reports.total??0))throw new Error('RESOLUTION_REQUIRES_CITIZEN_CONFIRMATION');}
 await db.query('BEGIN');try{await db.query(`UPDATE incidents SET status=$1,updated_at=now(),resolved_at=CASE WHEN $1='resolved' THEN now() ELSE resolved_at END WHERE id=$2`,[to,id]);await db.query(`INSERT INTO incident_history(incident_id,actor_user_id,event_type,details) VALUES($1,$2,'STATUS_CHANGED',$3)`,[id,actorId,JSON.stringify({from:current.status,to,note:note??null})]);await db.query('COMMIT');await calculateIncidentImpact(id);return {status:to};}catch(e){await db.query('ROLLBACK');throw e;}}
