import {db} from '../lib/database.js';
import {randomUUID} from 'node:crypto';
import {findCandidates} from '../clustering/service.js';
import {calculateIncidentImpact} from '../impact/service.js';
import {detectDepartmentCode} from './department-routing.js';
import {evaluateReportForAbuse} from '../abuse/service.js';
import type {ReportWorkStatus} from './types.js';
export async function createReport(input:{citizenId:string;categoryId:string;description:string;latitude:number;longitude:number;address?:string;wardId?:string;departmentId?:string;media?:{storageKey:string;mediaType:string;fileSize:number;dataUrl:string}[]}){
 const abuseCheck=await evaluateReportForAbuse(input.citizenId,input.description);
 if(abuseCheck.blocked){const err:any=new Error('REPORT_REJECTED_ABUSE_PROTECTION');err.reason=abuseCheck.reason;throw err;}
 const id=randomUUID(),incidentId=randomUUID();await db.query('BEGIN');
 try{const category=(await db.query(`SELECT code,department_id FROM issue_categories WHERE id=$1`,[input.categoryId])).rows[0];const routedDepartment=category?.code==='OTHER_PROBLEM'?detectDepartmentCode(input.description):null;const departmentId=input.departmentId??(routedDepartment ? (await db.query(`SELECT id FROM departments WHERE code=$1`,[routedDepartment])).rows[0]?.id : category?.department_id)??null;
 await db.query(`INSERT INTO incidents(id,category_id,department_id,ward_id,location,status) VALUES($1,$2,$3,$4,ST_SetSRID(ST_MakePoint($5,$6),4326),'open')`,[incidentId,input.categoryId,departmentId,input.wardId??null,input.longitude,input.latitude]);
 await db.query(`INSERT INTO reports(id,citizen_id,category_id,incident_id,department_id,ward_id,description,location,address,work_status) VALUES($1,$2,$3,$4,$5,$6,$7,ST_SetSRID(ST_MakePoint($8,$9),4326),$10,'REPORTED')`,[id,input.citizenId,input.categoryId,incidentId,departmentId,input.wardId??null,input.description,input.longitude,input.latitude,input.address??null]);
 for(const media of input.media??[]) await db.query(`INSERT INTO media_assets(report_id,storage_key,media_type,file_size,metadata) VALUES($1,$2,$3,$4,$5)`,[id,media.storageKey,media.mediaType,media.fileSize,JSON.stringify({dataUrl:media.dataUrl,source:'citizen_upload'})]);
 await db.query(`INSERT INTO report_status_history(report_id,actor_user_id,to_status) VALUES($1,$2,'REPORTED')`,[id,input.citizenId]);await db.query('COMMIT');
 const candidates=await findCandidates(id);const best=candidates.filter(x=>x.decision==='associated').sort((a,b)=>b.signals.confidence-a.signals.confidence)[0];
 if(best){await db.query('BEGIN');try{await db.query(`UPDATE reports SET incident_id=$1 WHERE id=$2`,[best.incidentId,id]);await db.query(`INSERT INTO incident_associations(report_id,incident_id,confidence,geographic_score,category_score,description_score,image_score,temporal_score,decision,explanation) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'associated',$9)`,[id,best.incidentId,best.signals.confidence,best.signals.geographicScore,best.signals.categoryScore,best.signals.descriptionScore,best.signals.imageScore,best.signals.temporalScore,JSON.stringify({...best.signals,reason:'same category plus geographic, temporal and description similarity'})]);await db.query(`DELETE FROM incidents WHERE id=$1 AND NOT EXISTS(SELECT 1 FROM reports WHERE incident_id=$1)`,[incidentId]);await db.query('COMMIT');await calculateIncidentImpact(best.incidentId);return {id,incidentId:best.incidentId,clustered:true,clusterConfidence:best.signals.confidence,departmentCode:routedDepartment};}catch(e){await db.query('ROLLBACK');throw e}}
 await calculateIncidentImpact(incidentId);
 return {id,incidentId,clustered:false,departmentCode:routedDepartment};
 }catch(e){await db.query('ROLLBACK');throw e}
}
export async function getReport(id:string){
 const {rows}=await db.query(`SELECT r.id,r.citizen_id AS "citizenId",r.category_id AS "categoryId",r.description,ST_Y(r.location) latitude,ST_X(r.location) longitude,r.address,r.work_status AS "workStatus",r.ward_id AS "wardId",r.department_id AS "departmentId",r.incident_id AS "incidentId",r.reported_at AS "reportedAt" FROM reports r WHERE r.id=$1`,[id]);
 const report=rows[0]; if(!report) return null;
 const comments=(await db.query(`SELECT id,body,created_at AS "createdAt" FROM report_comments WHERE report_id=$1 ORDER BY created_at`,[id])).rows;
 const feedback=(await db.query(`SELECT rating,body,created_at AS "createdAt" FROM report_feedback WHERE report_id=$1 ORDER BY created_at DESC`,[id])).rows;
 const media=(await db.query(`SELECT storage_key AS "storageKey",media_type AS "mediaType",file_size AS "fileSize",metadata FROM media_assets WHERE report_id=$1 ORDER BY created_at`,[id])).rows;
 const resolution=(await db.query(`SELECT s.note,s.submitted_at AS "submittedAt",v.overall_result AS "overallResult",v.confidence,v.evidence FROM resolution_submissions s JOIN resolution_verifications v ON v.submission_id=s.id WHERE s.incident_id=$1 ORDER BY v.created_at DESC LIMIT 1`,[report.incidentId])).rows[0] ?? null;
 const proof=(resolution ? (await db.query(`SELECT storage_key AS "storageKey",media_type AS "mediaType",captured_at AS "capturedAt",metadata FROM resolution_submission_media WHERE submission_id=(SELECT s.id FROM resolution_submissions s JOIN resolution_verifications v ON v.submission_id=s.id WHERE s.incident_id=$1 ORDER BY v.created_at DESC LIMIT 1)`,[report.incidentId])).rows : []);
 return {...report, comments, feedback, media, resolution:resolution ? {...resolution, media:proof} : null};
}
export async function listReports(citizenId:string){const {rows}=await db.query(`SELECT r.id,r.category_id AS "categoryId",r.description,r.work_status AS "workStatus",r.reported_at AS "reportedAt",r.incident_id AS "incidentId",r.address FROM reports r WHERE r.citizen_id=$1 ORDER BY r.reported_at DESC`,[citizenId]);return rows}
export async function findNearbyIncidents(input:{categoryId:string;latitude:number;longitude:number;description?:string}){const {rows}=await db.query(`SELECT i.id AS "incidentId",ic.name AS "categoryName",i.status,ROUND(ST_Distance(i.location::geography,ST_SetSRID(ST_MakePoint($2,$3),4326)::geography)::numeric,0)::int AS "distanceMeters",COUNT(DISTINCT r.id)::int AS "supportingReports",COUNT(DISTINCT rv.id)::int AS "supportingVotes",COALESCE((SELECT priority FROM incident_impact_scores s WHERE s.incident_id=i.id ORDER BY calculated_at DESC LIMIT 1),'LOW') AS priority FROM incidents i JOIN issue_categories ic ON ic.id=i.category_id LEFT JOIN reports r ON r.incident_id=i.id LEFT JOIN report_votes rv ON rv.report_id=r.id WHERE i.category_id=$1 AND i.location IS NOT NULL AND i.status IN ('open','verified','assigned','in_progress','pending_verification','reopened') AND ST_DWithin(i.location::geography,ST_SetSRID(ST_MakePoint($2,$3),4326)::geography,500) GROUP BY i.id,ic.name ORDER BY ST_Distance(i.location::geography,ST_SetSRID(ST_MakePoint($2,$3),4326)::geography) LIMIT 5`,[input.categoryId,input.longitude,input.latitude]);return rows}
