import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {db} from '../lib/database.js';
import {requireRole} from '../auth/middleware.js';
import {getCrossDepartmentIncident,setDepartments,updateTaskStatus} from './service.js';
const coordination=z.object({leadDepartmentId:z.string().uuid(),supportingDepartmentIds:z.array(z.string().uuid()).default([])});
const task=z.object({departmentId:z.string().uuid(),ownerUserId:z.string().uuid().optional(),title:z.string().min(2).max(240),description:z.string().max(4000).optional(),dueAt:z.string().datetime().optional()});
const status=z.object({status:z.enum(['PENDING','ASSIGNED','IN_PROGRESS','BLOCKED','COMPLETED','FAILED','CANCELLED'])});
const comment=z.object({body:z.string().trim().min(1).max(4000)});
export async function crossDepartmentRoutes(app:FastifyInstance){
 app.get('/incidents/:id/cross-department',{preHandler:requireRole('supervisor','administrator','officer')},async(req:any,reply)=>{const x=await getCrossDepartmentIncident(req.params.id);return x??reply.code(404).send({error:'INCIDENT_NOT_FOUND'});});
 app.put('/incidents/:id/cross-department',{preHandler:requireRole('supervisor','administrator')},async(req:any)=>{const x=coordination.parse(req.body);return setDepartments(req.params.id,req.user.id,x.leadDepartmentId,x.supportingDepartmentIds);});
 app.post('/incidents/:id/cross-department/tasks',{preHandler:requireRole('supervisor','administrator')},async(req:any,reply)=>{const x=task.parse(req.body);const member=(await db.query(`SELECT 1 FROM incident_departments WHERE incident_id=$1 AND department_id=$2`,[req.params.id,x.departmentId])).rows[0];if(!member)return reply.code(409).send({error:'DEPARTMENT_NOT_ASSIGNED'});if(x.ownerUserId){const owner=(await db.query(`SELECT 1 FROM worker_profiles WHERE user_id=$1 AND department_id=$2`,[x.ownerUserId,x.departmentId])).rows[0];if(!owner)return reply.code(409).send({error:'TASK_OWNER_WRONG_DEPARTMENT'});}const r=(await db.query(`INSERT INTO incident_tasks(incident_id,department_id,owner_user_id,title,description,status,due_at,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[req.params.id,x.departmentId,x.ownerUserId??null,x.title,x.description??null,x.ownerUserId?'ASSIGNED':'PENDING',x.dueAt??null,req.user.id])).rows[0];await db.query(`INSERT INTO incident_task_history(task_id,actor_user_id,new_status,event_type,details) VALUES($1,$2,$3,'TASK_CREATED',$4)`,[r.id,req.user.id,x.ownerUserId?'ASSIGNED':'PENDING',JSON.stringify(x)]);return reply.code(201).send(r);});
 app.patch('/cross-department/tasks/:id/status',{preHandler:requireRole('officer','supervisor','administrator')},async(req:any,reply)=>{try{return await updateTaskStatus(req.params.id,req.user.id,status.parse(req.body).status);}catch(e:any){if(e.message==='TASK_FORBIDDEN')return reply.code(403).send({error:e.message});if(e.message.startsWith('INVALID_TASK'))return reply.code(409).send({error:e.message});throw e;}});
 app.post('/cross-department/tasks/:id/reassign',{preHandler:requireRole('supervisor','administrator')},async(req:any,reply)=>{const x=z.object({ownerUserId:z.string().uuid().nullable()}).parse(req.body);const t=(await db.query(`SELECT incident_id,department_id FROM incident_tasks WHERE id=$1`,[req.params.id])).rows[0];if(!t)return reply.code(404).send({error:'TASK_NOT_FOUND'});if(x.ownerUserId){const ok=(await db.query(`SELECT 1 FROM worker_profiles WHERE user_id=$1 AND department_id=$2 AND availability_status='AVAILABLE'`,[x.ownerUserId,t.department_id])).rows[0];if(!ok)return reply.code(409).send({error:'INVALID_TASK_OWNER'});}await db.query(`UPDATE incident_tasks SET owner_user_id=$1,status=CASE WHEN $1 IS NULL THEN 'PENDING' ELSE 'ASSIGNED' END,updated_at=now() WHERE id=$2`,[x.ownerUserId,req.params.id]);await db.query(`INSERT INTO incident_task_history(task_id,actor_user_id,event_type,details) VALUES($1,$2,'REASSIGNED',$3)`,[req.params.id,req.user.id,JSON.stringify(x)]);await db.query(`INSERT INTO incident_department_audit(incident_id,department_id,actor_user_id,action,details) VALUES($1,$2,$3,'TASK_REASSIGNED',$4)`,[t.incident_id,t.department_id,req.user.id,JSON.stringify(x)]);return {reassigned:true};});
 app.post('/cross-department/tasks/:id/comments',{preHandler:requireRole('officer','supervisor','administrator')},async(req:any,reply)=>{const x=comment.parse(req.body);const t=(await db.query(`SELECT incident_id FROM incident_tasks WHERE id=$1`,[req.params.id])).rows[0];if(!t)return reply.code(404).send({error:'TASK_NOT_FOUND'});const r=(await db.query(`INSERT INTO incident_task_comments(task_id,author_user_id,body) VALUES($1,$2,$3) RETURNING id,body,created_at AS "createdAt"`,[req.params.id,req.user.id,x.body])).rows[0];return reply.code(201).send(r);});
}
