import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {requireRole} from '../auth/middleware.js';
import {db} from '../lib/database.js';
import {submitResolution,verifyResolution} from './service.js';
import {calculateIncidentImpact} from '../impact/service.js';
const media=z.object({storageKey:z.string().min(1),sha256:z.string().optional(),capturedAt:z.string().datetime().optional(),mediaType:z.string().optional(),valid:z.boolean().optional(),dataUrl:z.string().regex(/^data:image\/(png|jpeg|jpg|webp);base64,/i).max(11000000).optional()});
const submit=z.object({resolutionLatitude:z.number().min(-90).max(90).nullable(),resolutionLongitude:z.number().min(-180).max(180).nullable(),note:z.string().max(2000).optional(),media:z.array(media).default([])});
const review=z.object({decision:z.enum(['APPROVE','REJECT','REQUEST_EVIDENCE']),note:z.string().max(2000).optional()});
export async function verificationRoutes(app:FastifyInstance){
 app.post('/incidents/:id/resolution-verification',{preHandler:requireRole('officer','supervisor','administrator')},async(req:any,reply)=>{const x=submit.parse(req.body);return reply.code(201).send(await submitResolution({incidentId:req.params.id,actorId:req.user.id,...x}));});
 app.get('/incidents/:id/verification',{preHandler:requireRole('officer','supervisor','administrator')},async(req:any)=>{const {rows}=await db.query(`SELECT v.*,s.submitted_at AS "submittedAt",s.resolution_latitude AS "resolutionLatitude",s.resolution_longitude AS "resolutionLongitude",s.note FROM resolution_verifications v JOIN resolution_submissions s ON s.id=v.submission_id WHERE s.incident_id=$1 ORDER BY v.created_at DESC`,[req.params.id]);if(!rows[0])return null;const checks=(await db.query(`SELECT check_type AS "checkType",result,confidence,evidence,algorithm_version AS "algorithmVersion" FROM resolution_verification_checks WHERE verification_id=$1 ORDER BY check_type`,[rows[0].id])).rows;const media=(await db.query(`SELECT storage_key AS "storageKey",media_type AS "mediaType",captured_at AS "capturedAt",sha256,metadata FROM resolution_submission_media WHERE submission_id=$1`,[rows[0].submission_id])).rows;const original=(await db.query(`SELECT storage_key AS "storageKey",media_type AS "mediaType",created_at AS "capturedAt" FROM report_evidence WHERE report_id IN (SELECT id FROM reports WHERE incident_id=$1)`,[req.params.id])).rows;const subsequent=(await db.query(`SELECT id,reported_at AS "reportedAt",description,category_id AS "categoryId" FROM reports WHERE incident_id=$1 AND reported_at>$2 ORDER BY reported_at`,[req.params.id,rows[0].submittedAt])).rows;return {...rows[0],checks,media,originalMedia:original,subsequentReports:subsequent};});
 app.post('/verification/:id/review',{preHandler:requireRole('supervisor','administrator')},async(req:any,reply)=>{const x=review.parse(req.body);const v=(await db.query(`SELECT rv.id,s.incident_id FROM resolution_verifications rv JOIN resolution_submissions s ON s.id=rv.submission_id WHERE rv.id=$1`,[req.params.id])).rows[0];if(!v)return reply.code(404).send({error:'VERIFICATION_NOT_FOUND'});await db.query(`INSERT INTO resolution_verification_reviews(verification_id,reviewer_user_id,decision,note) VALUES($1,$2,$3,$4)`,[req.params.id,req.user.id,x.decision,x.note??null]);const status=x.decision==='REJECT'?'flagged':'pending_verification';await db.query(`UPDATE incidents SET status=$1,updated_at=now() WHERE id=$2`,[status,v.incident_id]);await db.query(`INSERT INTO incident_history(incident_id,actor_user_id,event_type,details) VALUES($1,$2,'RESOLUTION_REVIEWED',$3)`,[v.incident_id,req.user.id,JSON.stringify({verificationId:req.params.id,decision:x.decision,note:x.note??null,nextStatus:status})]);await calculateIncidentImpact(v.incident_id);return {reviewed:true,status};});
}
