import {db} from '../lib/database.js';
import {calculateIncidentImpact} from '../impact/service.js';
import type {CheckInput,MediaEvidence,SubsequentReport,VerificationInput} from './types.js';
const VERSION='resolution-verification-v1',GPS_METERS=100;
function distanceMeters(aLat:number,aLon:number,bLat:number,bLon:number){const R=6371000,rad=Math.PI/180,dLat=(bLat-aLat)*rad,dLon=(bLon-aLon)*rad;const x=Math.sin(dLat/2)**2+Math.cos(aLat*rad)*Math.cos(bLat*rad)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function gps(i:VerificationInput):CheckInput{if([i.incidentLatitude,i.incidentLongitude,i.resolutionLatitude,i.resolutionLongitude].some(v=>v==null))return {type:'GPS_PROXIMITY',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'GPS unavailable'}};const d=distanceMeters(i.incidentLatitude!,i.incidentLongitude!,i.resolutionLatitude!,i.resolutionLongitude!);return {type:'GPS_PROXIMITY',result:d<=GPS_METERS?'PASS':'FAIL',confidence:1,evidence:{distanceMeters:d,thresholdMeters:GPS_METERS}};}
function media(i:VerificationInput):CheckInput{if(!i.resolutionMedia?.length)return {type:'MEDIA_VALIDITY',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'No resolution media'}};const invalid=i.resolutionMedia.filter(x=>x.valid===false);return {type:'MEDIA_VALIDITY',result:invalid.length?'FAIL':'PASS',confidence:1,evidence:{count:i.resolutionMedia.length,invalidCount:invalid.length}};}
function timestamps(i:VerificationInput):CheckInput{const a=Date.parse(i.submittedAt),b=Date.parse(i.incidentCreatedAt);if(!Number.isFinite(a)||!Number.isFinite(b))return {type:'TIMESTAMP_CONSISTENCY',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'Invalid timestamp'}};return {type:'TIMESTAMP_CONSISTENCY',result:a>=b?'PASS':'FAIL',confidence:1,evidence:{incidentCreatedAt:i.incidentCreatedAt,submittedAt:i.submittedAt}};}
function imageChange(i:VerificationInput):CheckInput{if(!i.originalMedia?.length||!i.resolutionMedia?.length)return {type:'IMAGE_CHANGE',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'Both image sets unavailable'}};const same=i.resolutionMedia.some(r=>i.originalMedia!.some(o=>o.sha256&&r.sha256&&o.sha256===r.sha256));return {type:'IMAGE_CHANGE',result:same?'FAIL':'PASS',confidence:1,evidence:{matchedHash:same,method:'sha256-equality-only'}};}
function reused(i:VerificationInput):CheckInput{const hashes=(i.resolutionMedia??[]).map(x=>x.sha256).filter(Boolean) as string[];if(!hashes.length)return {type:'REUSED_IMAGE',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'Resolution hash unavailable'}};return {type:'REUSED_IMAGE',result:'PASS',confidence:1,evidence:{hashesChecked:hashes.length}};}
function subsequent(i:VerificationInput):CheckInput{if(!i.subsequentReports)return {type:'SUBSEQUENT_REPORTS',result:'INCONCLUSIVE',confidence:null,evidence:{reason:'Subsequent reports unavailable'}};const after=i.subsequentReports.filter(r=>Date.parse(r.reportedAt)>Date.parse(i.submittedAt));return {type:'SUBSEQUENT_REPORTS',result:after.length?'FAIL':'PASS',confidence:1,evidence:{subsequentReportCount:after.length}};}
export function verifyResolution(i:VerificationInput){const checks=[gps(i),media(i),timestamps(i),imageChange(i),reused(i),subsequent(i)],fails=checks.filter(x=>x.result==='FAIL').length,passes=checks.filter(x=>x.result==='PASS').length,usable=checks.filter(x=>x.result!=='INCONCLUSIVE').length;let overall:'PASS'|'FAIL'|'INCONCLUSIVE'|'POTENTIALLY_UNRESOLVED'=fails?'FAIL':usable<4?'INCONCLUSIVE':passes===usable?'PASS':'POTENTIALLY_UNRESOLVED';const confidence=usable?Math.max(0,Math.min(1,(passes-fails*.5)/usable)):0;return {overall,confidence,checks,algorithmVersion:VERSION};}

export async function submitResolution(input:{incidentId:string;actorId:string;resolutionLatitude:number|null;resolutionLongitude:number|null;note?:string;media:MediaEvidence[]}){
 const incident=(await db.query(`SELECT ST_Y(location) latitude,ST_X(location) longitude,created_at FROM incidents WHERE id=$1`,[input.incidentId])).rows[0];if(!incident)throw new Error('INCIDENT_NOT_FOUND');
 const original=(await db.query(`SELECT storage_key,media_type,created_at AS captured_at FROM report_evidence WHERE report_id IN (SELECT id FROM reports WHERE incident_id=$1)`,[input.incidentId])).rows;
 const originalMedia:MediaEvidence[]=original.map((m:any)=>({storageKey:m.storage_key,mediaType:m.media_type,capturedAt:m.captured_at,sha256:m.metadata?.sha256??null,valid:true}));
 const submittedAt=new Date().toISOString();await db.query(`UPDATE incidents SET status='pending_verification',updated_at=now() WHERE id=$1`,[input.incidentId]);
 const previousHashes=(await db.query(`SELECT DISTINCT sha256 FROM resolution_submission_media WHERE sha256 IS NOT NULL AND storage_key IS NOT NULL`,[])).rows.map((r:any)=>r.sha256);
 const reused=input.media.some(m=>m.sha256&&previousHashes.includes(m.sha256));
 const subsequent:SubsequentReport[]=[];
 const result=verifyResolution({incidentLatitude:incident.latitude,incidentLongitude:incident.longitude,resolutionLatitude:input.resolutionLatitude,resolutionLongitude:input.resolutionLongitude,originalMedia,resolutionMedia:input.media,submittedAt,incidentCreatedAt:incident.created_at,subsequentReports:subsequent});
 if(reused){const c=result.checks.find(x=>x.type==='REUSED_IMAGE');if(c){c.result='FAIL';c.confidence=1;c.evidence={reused:true,scope:'previous_resolution_submissions'};}result.overall='FAIL';}
 await db.query('BEGIN');try{
  const sub=(await db.query(`INSERT INTO resolution_submissions(incident_id,submitted_by_user_id,resolution_latitude,resolution_longitude,submitted_at,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[input.incidentId,input.actorId,input.resolutionLatitude,input.resolutionLongitude,submittedAt,input.note??null])).rows[0];
  for(const m of input.media)await db.query(`INSERT INTO resolution_submission_media(submission_id,storage_key,media_type,captured_at,sha256,metadata) VALUES($1,$2,$3,$4,$5,$6)`,[sub.id,m.storageKey,m.mediaType??null,m.capturedAt??null,m.sha256??null,JSON.stringify({mediaType:m.mediaType??null,valid:m.valid??true,dataUrl:m.dataUrl??null})]);
  const ver=(await db.query(`INSERT INTO resolution_verifications(submission_id,overall_result,confidence,algorithm_version,evidence) VALUES($1,$2,$3,$4,$5) RETURNING id`,[sub.id,result.overall,result.confidence,result.algorithmVersion,JSON.stringify({checks:result.checks})])).rows[0];
  for(const c of result.checks)await db.query(`INSERT INTO resolution_verification_checks(verification_id,check_type,result,confidence,evidence,algorithm_version) VALUES($1,$2,$3,$4,$5,$6)`,[ver.id,c.type,c.result,c.confidence,JSON.stringify(c.evidence),result.algorithmVersion]);
  const next=result.overall==='PASS'?'resolved':result.overall==='FAIL'?'flagged':'pending_verification';await db.query(`UPDATE incidents SET status=$1,updated_at=now() WHERE id=$2`,[next,input.incidentId]);
  await db.query(`INSERT INTO incident_history(incident_id,actor_user_id,event_type,details) VALUES($1,$2,'RESOLUTION_VERIFICATION',$3)`,[input.incidentId,input.actorId,JSON.stringify({verificationId:ver.id,overall:result.overall,confidence:result.confidence})]);await db.query('COMMIT');await calculateIncidentImpact(input.incidentId);return {submissionId:sub.id,verificationId:ver.id,...result};
 }catch(e){await db.query('ROLLBACK');throw e;}
}
